### ISSUE TITLE
LeaveTimeOut not working

### ISSUE THREAD

**Issue by lerdy** [galnir/Master-Bot#639] opened 2021-09-26 04:09 UTC
**Describe the bug**
I saw some other dude had this issue opened but he didn't actually provide any info so i'm opening a different one. Sorry if that's not right..
When playing a song the bot leaves immediately instead of waiting the 300 seconds define in the options.json.

**To Reproduce**
1. Queue a song
2. Wait for it to finish
3. Bot leaves at the end of song instead of waiting

**Expected behavior**
Bot should wait 300 seconds before leaving the vc

**Screenshots**
https://cdn.discordapp.com/attachments/885480544417222660/891536057064120340/issue.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 
 - Node Version: 16.10.0
 - Is python 2.7 installed?: Yes
 - How are you hosting the bot: vps

**Additional context**
{
  "playLiveStreams": true,
  "playVideosLongerThan1Hour": true,
  "maxQueueLength": 1000,
  "AutomaticallyShuffleYouTubePlaylists": false,
  "LeaveTimeOut": 300,
  "MaxResponseTime": 30,
  "deleteOldPlayMessage": true
}

**Comment by galnir** [comment] 2021-09-26 07:11
duplicate of #608 
I'll work on that soon

**Closed by galnir** 2021-09-26 07:11 UTC
Labels: bug
