### ISSUE TITLE
Multi Lanugages

### ISSUE THREAD

**Issue by TrueMB** [galnir/Master-Bot#661] opened 2021-11-20 14:51 UTC
It would be awesome, if the Bot got a multi language Support.
Like a MessageManager (maybe even for different guilds), but mainly away from the code.
I often got the problems, if I want to update my own bot and the language is english again.

The same if I want to push something in this repo. I fixed some stuff with in the play command and added the seek option again. But since its german, it wont be helpful.

/resources/languages/default.lang
/resources/languages/german.lang

Something like this structure would be nice

**Comment by galnir** [comment] 2021-12-25 12:19
duplicate of #598 added to feature list #667

**Closed by galnir** 2021-12-25 12:19 UTC
Labels: enhancement
