### ISSUE TITLE
Hello, when i attempt to play a song with the bot it replies saying "I do not have permissions to join the voicechannel" the thing that is confusing me however is the fact that it has perms to join and the bot role which has Administrator turned on, also just before it says the error message it joins the vc but leaves straightaway any ideas on what this is? 

### ISSUE THREAD

**Issue by yeet5541** [galnir/Master-Bot#448] opened 2021-02-10 12:24 UTC
hmmm

**Comment by galnir** [comment] 2021-02-10 16:58
Fill the issue template please

**Comment by Natemo6348** [comment] 2021-02-10 17:11
without the issue template, I'm left to assume that it could be ffmpeg-static not installing correctly, usually what causes that issue for me

**Comment by BradChism** [comment] 2021-02-11 09:49
Not looking to Hijack the thread but I am supporting yeet5541's claim with this as I can confirm on Ubuntu that this error continues. 

Installed/Running: 
Ubuntu/Kabuntu: 20.04
ffmpeg-static: 4.3.1
Node 15.0 
Python: 2.7.18

I grabbed this directly from github and did the npm i updates directly and didn't copy a single command from the working previous versions of the bot to recreate this error. 

Error in Chat:

(red X) There was  problem searching the video requested!
(red X) I had some trouble finding what you were looking for, please try again or be more specific

Command used: !play ACDC

In YouTube using my API Key in the dashboard, I get Requests (currently up to 11) Errors (%) 100 , Latency (ms), median & Latency, 95% (ms)

Now I am using V.3 of YouTubes API Keys. 

Also if this helps: youtube.api.v3.V3DataSearchService.List 100% Error
Traffic By Response Code: 403
Youtube API 403 exceeed

Looking deeper, it's with Quota's,
 YouTube changed Queries per day to 0
Queries per 100 seconds per user: 300,000
Queries per 100 seconds: 3,000,000

**- And as I was writing this... The solution.. 

Go make a new Project with YouTube. If it's been over 90 days since you used your last key or YT finds it not active, they will 0 out your quota and the key and project will stop working. 

Delete all old projects and make a new one and then you should be good to go.**

**Comment by galnir** [comment] 2021-02-12 20:36
I'm closing this so you can open a new issue and fill the template this time

**Closed by galnir** 2021-02-12 20:36 UTC
Labels: bug
