### ISSUE TITLE
Hello i have issue bot not joined voice channel and cant play song.

### ISSUE THREAD

**Issue by Bartholomeouw** [galnir/Master-Bot#55] opened 2020-04-24 15:47 UTC
![Screenshot_20200424_225100](https://user-images.githubusercontent.com/48173337/80232031-6cf1ab00-867e-11ea-9e6e-bdfede8c5453.png)

**Comment by galnir** [comment] 2020-04-24 17:10
From the lyrics command error I can infer you didn't place correct API keys in config.json

**Comment by galnir** [comment] 2020-04-24 17:11
And also update your nodejs version to v12 atleast

**Comment by galnir** [comment] 2020-04-25 07:25
@Bartholomeouw Did it work?

**Comment by zoranzoki21** [comment] 2020-04-27 18:51
I have problem that bot joins to channel, but there isn't sound. I host it on Heroku.

**Comment by galnir** [comment] 2020-04-28 16:02
@zoranzoki21 Are you still getting it? If you install everything like I told you in another thread, there is no reason it wouldn't work. Almost always the problem is node-opus if the bot joins the channel but doesn't play the song. Hit `npm i node-opus` and make sure it doesn't fail

Closing this since OP doesn't respond

**Closed by galnir** 2020-04-28 16:02 UTC
