### ISSUE TITLE
LeaveTimeOut not working

### ISSUE THREAD

**Issue by Sancoraa** [galnir/Master-Bot#642] opened 2021-09-29 01:42 UTC
### IMPORTANT : *DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE*

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]:
 - Node.js Version(Should be v16 at least): 
 - Is python 2.7 installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Describe the bug**
Whatever the value I set for LeaveTimeOut, the bot ignores it and leaves at the end of any song.

**To Reproduce**
Set the LeaveTimeOut to a value greater than 1

**Comment by galnir** [comment] 2021-09-29 10:25
Duplicate of #608 
I promised to look into it soon :)

**Closed by galnir** 2021-09-29 10:25 UTC
Labels: bug
